### ISSUE TITLE
Fix spelling

### ISSUE THREAD

**Issue by martinmoene** [janwilmans/guidelines#1]
"_The whitespace in the examples below is **~~arbiraty~~ arbitrary** but consistent._"

**Comment by janwilmans** [comment]
fixed by 324f0c5

**Comment by janwilmans** [comment]
thanks for reminding me to run a spell checker ;)

**Comment by janwilmans** [comment]
would you like to do another review? I would welcome any comments

**Comment by martinmoene** [comment]
Yeah, will do.
